export default {
    FETCH_MOVIES_START: 'FETCH_MOVIES_START',
    FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
    FETCH_MOVIES_ERROR: 'FETCH_MOVIES_ERROR',
    RESET_MOVIES_PAGE: 'RESET_MOVIES_PAGE',
    UPDATE_MOVIES_PAGE: 'UPDATE_MOVIES_PAGE',
    DOWNGRADE_MOVIES_PAGE: 'DOWNGRADE_MOVIES_PAGE',
};
